data:
    flickr:
        dataset: flickr
        base_directory: '/flickr_8k'
        train_images_file: '/flickr_8k/Flickr_8k.trainImages.txt'
        test_images_file: '/flickr_8k/Flickr_8k.testImages.txt'
        validation_images_file: '/flickr_8k/Flickr_8k.devImages.txt'
        descriptions: '/flickr_8k/Flickr8k.token.txt'
        dataset_path: '/flickr_8k/Flicker8k_Dataset'
    googlecc:
        dataset: googlecc
        index_file: '/dataset/google-cc/100k/images/index_file.txt'
        train_images_file: '/dataset/google-cc/100k/trainImages.txt'
        test_images_file: '/dataset/google-cc/100k/testImages.txt'
        validation_images_file: '/dataset/google-cc/100k/validationImages.txt'
        descriptions: '/dataset/google-cc/train_GCC-training.tsv'
        dataset_path: '/dataset/google-cc/100k/images'