model:
    name: inception_lstm_inject_with_threshold
    arch_type: cnn_lstm_inject

dataset:
    name: google-cc-100k-with-threshold
    encoding: inception
    is_threshold: True

language:
    max_sentence_length: 40
    embedding_dimension: 300

training:
    batch_size: 40
    epochs: 40

validation:
    batch_size: 40

workspace:
    directory: '/workspace/'