model:
    arch: inception_lstm_autoencoder
dataset:
    name: google-cc-10k

language:
    max_sentence_length: 40
    embedding_dimension: 300

training:
    batch_size: 40
    epochs: 40

validation:
    batch_size: 40

workspace:
    directory: '/workspace/'