model:
    arch: inception_lstm_no_threshold
dataset:
    name: google-cc-100k-no-threshold

language:
    max_sentence_length: 40
    embedding_dimension: 300

training:
    batch_size: 40
    epochs: 40

validation:
    batch_size: 40

workspace:
    directory: '/workspace/'