model:
    arch: inception_lstm

language:
    max_sentence_length: 40
    embedding_dimension: 300

training:
    batch_size: 1000
    epochs: 20

validation:
    batch_size: 40

workspace:
    directory: 'C:\Users\smadh\Desktop\Assignments\big-data-analytics\data\flickr\models'

