model:
    name: resnet_lstm_merge_no_threshold
    arch_type: cnn_lstm_merge

dataset:
    name: google-cc-100k-no-threshold
    encoding: resnet50
    is_threshold: False

language:
    max_sentence_length: 40
    embedding_dimension: 300

training:
    batch_size: 40
    epochs: 40

validation:
    batch_size: 40

workspace:
    directory: '/workspace/'