model:
    name: resnet_lstm_autoencoder
    arch_type: resnet_lstm_autoencoder

dataset:
    name: google-cc-100k-with-threshold
    encoding: simple
    is_threshold: False

language:
    max_sentence_length: 40
    embedding_dimension: 300

training:
    batch_size: 40
    epochs: 40

validation:
    batch_size: 40

workspace:
    directory: '/workspace/'